### PR TITLE
🐛 [RUMF-931] check if PerformanceEntry is defined before using it

### LINKED ISSUE #890: `ReferenceError Can't find variable: PerformanceEntry` error on MacOS Safari and Mobile Safari
Hi,

We are experiencing a few exceptions when running the most recent version of the Datadog RUM SDK and it looks like a compatibility issue with older Safari versions when trying to use the `PerformanceEntry` API.

Versions affected in our end:

```
MacOS Safari - 10.1.2
Mobile Safari - 10.0.0
```

Here is the stacktrace:

```
ReferenceError Can't find variable: PerformanceEntry 
    https://www.datadoghq-browser-agent.com/datadog-rum.js:1:48530 
    https://www.datadoghq-browser-agent.com/datadog-rum.js:1:48630 
    [native code] forEach
    https://www.datadoghq-browser-agent.com/datadog-rum.js:1:22279 notify
    https://www.datadoghq-browser-agent.com/datadog-rum.js:1:38890 
    [native code] forEach
    https://www.datadoghq-browser-agent.com/datadog-rum.js:1:35971 
    https://www.datadoghq-browser-agent.com/datadog-rum.js:1:1188 
    https://www.datadoghq-browser-agent.com/datadog-rum.js:1:36102 n
    node_modules/core-js/modules/es.promise.js:114:29 
    node_modules/core-js/internals/microtask.js:27:8 flush
```

Should that versions be supported by the SDK? If so, could you help providing a fix?

Thanks

### PR DESCRIPTION
**Pull request by BenoitZugmeyer**
## Motivation

When implementing #883, we needed to use the global `PerformanceEntry` class. This class is not supported in Safari 10 and below.
Fix #890 

## Changes

Check if `PerformanceEntry` is defined before using it.

## Testing

CI, manual (browser stack live with Safari 10)

## Note

This should have been an internal error, but because of the [`await` used in the `fetchProxy`](https://github.com/DataDog/browser-sdk/blob/57cf9bba92e6bfea6a0877d208155495d671df68/packages/core/src/browser/fetchProxy.ts#L124), it ends up as an "unhandled rejection" (anything executed after the await is not "monitored"). We should address this issue in a separate PR.

---

I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/main/CONTRIBUTING.md) documentation.

### CODE REVIEW

File: packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts [hunk 1]
```diff
@@ -127,3 +133,11 @@ function computeRequestTracingInfo(request: RequestCompleteEvent) {
 function computeEntryTracingInfo(entry: RumPerformanceResourceTiming) {
   return entry.traceId ? { _dd: { trace_id: entry.traceId } } : undefined
 }
+
+function toPerformanceEntryRepresentation(entry: RumPerformanceEntry): PerformanceEntryRepresentation {
+  // Safari 10 doesn't support PerformanceEntry
+  if (typeof PerformanceEntry === 'function' && entry instanceof PerformanceEntry) {
```
Comment (amortemousque) [inline packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts:139]: Maybe grouping compatibility check functions like` isPermanceEntryAvailable() `somewhere in `/core` can provide meaningful naming and better reusability?

**Review by bcaudan — APPROVED** [review]

File: packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts (hunk 1 above)
Comment (BenoitZugmeyer) [reply packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts]: I moved in with similar functions related to "performance" support. I think we shouldn't polute "core" with functions that are only used in "rum". Let me know what you think :)

Comment (amortemousque) [reply packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts]: Good for me ;)

**Review by amortemousque — APPROVED** [review]
